conf/settings/base.py
deploy/roles/maintenance/tasks/main.yml

Closes #86 
- Setea el timezone en los settings de django
- Setea el timezone en los tasks de maintenance para el deploy

86 fix timezones

---

monitoreo/apps/dashboard/models.py
monitoreo/apps/dashboard/tests/models_test.py

Closes #100 
- Ordena los indicadores no numéricos por valor de manera descendente.
- Modifica el test de comportamiento de manera acorde.

100 ordenar indicadores no numericos

---

monitoreo/apps/dashboard/admin.py

- Agrega 2 botones para mover los indicadores al tope o al fondo de la lista.

Agrega botones para mandar al tope o al fondo los indicator types

---

monitoreo/apps/dashboard/admin.py
monitoreo/apps/dashboard/tasks.py

- Cambios al admin y task para que FederationAdmin use el save model de AbstractTask
- Corrección al `callable_str` del admin de envío de reportes

Bugfix en save_model de FederationTask

---

monitoreo/apps/dashboard/report_tasks.py

Cambia el timezone al del server antes de pedir el date

Report timezone fix

---

monitoreo/apps/dashboard/report_tasks.py
monitoreo/apps/dashboard/tests/report_tests.py

Closes #121 
- Atrapa excepciones de la generación del `data.json` en `send_validations`.
- Cambia el subject del mail y agrega el xlsx de validación como attachment.
- Agrega y modifica tests del mail

attachment de xlxs y fix de subject

---

monitoreo/apps/dashboard/report_tasks.py
monitoreo/apps/dashboard/tests/report_tests.py
monitoreo/templates/reports/report.html
monitoreo/templates/reports/report.txt

Closes #129 
- Agrega la info del task al principio del mail
- Actualiza los tests

129 logs reporte indicadores

---

deploy/roles/django_application/tasks/main.yml
deploy/roles/django_application/tasks/setup_worker_maintenance_cron.yml
monitoreo/apps/dashboard/helpers.py

Closes datosgobar/django-datajsonar#80
- Agrega task de ansible para restartear los workers en deploy

Restart workers on deploy

---

conf/settings/base.py
monitoreo/apps/dashboard/indicators_tasks.py
monitoreo/apps/dashboard/tasks.py
requirements/base.txt

Actualiza la versión de `django_datajsonar` con los cambios necesarios

Django datajsonar synchros update

---

deploy/roles/django_application/tasks/setup_maintenance_crons.yml

closes datosgobar/django-datajsonar#80

cambio el horario de mantenimiento

---

monitoreo/apps/dashboard/report_tasks.py

closes #156 
Abre una conexión en el `ReportSender` y la cierra una vez que termina la tarea. Esa conexión se utiliza para mandar todos los mails.

Reutilizo la conexión smtp para el envio de mails

---

.travis.yml
deploy/roles/django_application/tasks/setup_python_env.yml
monitoreo/apps/dashboard/admin/__init__.py
monitoreo/apps/dashboard/admin/tasks.py
monitoreo/apps/dashboard/helpers.py
monitoreo/apps/dashboard/indicators_tasks.py
monitoreo/apps/dashboard/management/commands/import_indicators.py
monitoreo/apps/dashboard/migrations/0028_populate_indicador_jurisdiccion_id.py
monitoreo/apps/dashboard/migrations/0029_populate_ids_faltantes.py
monitoreo/apps/dashboard/migrations/0031_populate_ids.py
monitoreo/apps/dashboard/report_tasks.py
monitoreo/apps/dashboard/tasks.py
monitoreo/apps/dashboard/tests/models_test.py
monitoreo/apps/dashboard/tests/report_tests.py
monitoreo/apps/dashboard/tests/tasks_test.py
monitoreo/apps/dashboard/tests/test_utils/read_bytes_as_csv.py
monitoreo/apps/dashboard/tests/views_test.py
monitoreo/apps/dashboard/views.py
requirements/testing.txt

Pasa a correr la aplicación bajo python 3.

Python3 migration

---

monitoreo/apps/dashboard/indicators_tasks.py
monitoreo/apps/dashboard/tests/commands_test.py
monitoreo/apps/dashboard/tests/indicators_tasks_test.py

161 usar nuevos indicadores federacion

---

monitoreo/apps/dashboard/email_renderer.py
monitoreo/apps/dashboard/report_generators.py
monitoreo/apps/dashboard/report_tasks.py
monitoreo/apps/dashboard/tests/indicators_report_tests.py
monitoreo/apps/dashboard/tests/validation_report_tests.py
monitoreo/templates/reports/indicators.html

Closes #131 
- Refactor del código para enviar reportes de indicadores e inclusión de los indicadores del nodo central
- Refactor de los tests e inclusión del caso de indicadores del nodo central

131 reporte indicadores nodo federador

---

monitoreo/apps/dashboard/custom_generators.py
monitoreo/apps/dashboard/echo.py
monitoreo/apps/dashboard/helpers.py
monitoreo/apps/dashboard/tests/custom_generators_test.py
monitoreo/apps/dashboard/tests/helpers_test.py
monitoreo/apps/dashboard/urls.py
monitoreo/apps/dashboard/views.py

Closes #184 
- Crea un nuevo url con su respectivo controller que devuelve el archivo CSV de Indicadores de Red como una StreamingHttpResponse de Django. También crea una nueva función y una clase necesarias para el controller

184  Implementar CSV (panel) de indicadores de red

---

deploy/deploy.sh

Agrego script de deploy

---

monitoreo/apps/dashboard/custom_generators.py
monitoreo/apps/dashboard/models/indicators.py
monitoreo/apps/dashboard/tests/custom_generators_test.py
monitoreo/apps/dashboard/tests/views_test.py
monitoreo/apps/dashboard/urls.py
monitoreo/apps/dashboard/views.py

Crea dos CSV nuevos con los datos de los modelos `Indicador` e `IndicadorFederador`:
- /indicadores-nodos.csv
- /indicadores-federadores.csv
Closes #183

183 implementar csv nodos indicadores

---

monitoreo/static/css/styles.css

Agrego background para el header del login

---

monitoreo/apps/dashboard/helpers.py
monitoreo/apps/dashboard/tests/helpers_test.py
monitoreo/apps/dashboard/tests/views_test.py
monitoreo/apps/dashboard/urls.py
monitoreo/apps/dashboard/views.py

Borro landing page de dashboard de urls

---

conf/settings/base.py
monitoreo/static/css/styles.css
monitoreo/templates/admin/login.html
monitoreo/urls.py

routeo y settings para recuperar contraseñas

---

monitoreo/apps/dashboard/helpers.py
monitoreo/apps/dashboard/report_generators.py
monitoreo/apps/dashboard/tasks.py
monitoreo/apps/dashboard/tests/helpers_test.py
monitoreo/apps/dashboard/tests/validation_report_tests.py

Closes #212 
Pasa el catalog format del nodo a los DataJson en el cálculo de indicadores

212 formato dj calculo indicadores

---

conf/settings/base.py
monitoreo/apps/dashboard/admin/indicators.py
monitoreo/apps/dashboard/management/import_utils.py
monitoreo/apps/dashboard/tests/import_export_test.py
requirements/base.txt

Closes #210 
- Hace la validación de datos de manera asincrónica
- Recrea la tabla de indicadores en lugar de hacer un upsert
- Actualiza los tests con el comportamiento nuevo

210 indicator imports reestructure

---

monitoreo/apps/dashboard/indicators_tasks.py
monitoreo/apps/dashboard/models/querysets.py

Closes #222 
- Agrega timeout a la tarea de escritura de archivos
- Atrapa el caso de que no se pueda leer el valor de un indicador

Fix time series generation

---

monitoreo/apps/dashboard/custom_generators.py
monitoreo/apps/dashboard/models/indicators.py
monitoreo/apps/dashboard/tests/custom_generators_test.py
monitoreo/apps/dashboard/tests/views_test.py

Closes #219 
- Reorganiza el csv de indicadores agregando la columna `indicador_apertura`
- Actualiza los tests para tener en cuenta este nuevo formato

219 apertura csv indicadores

---

monitoreo/templates/reports/newly.html
monitoreo/templates/reports/newly.txt

Agrego fecha y hora en el mail de reporte de novedades, para un nodo particular

---

monitoreo/apps/dashboard/email_renderer.py
monitoreo/apps/dashboard/tests/newly_dataset_report_tests.py

- Agrego al remitente en CCO para todos los mails de reportes  que se mandan
- Agrego un test

Se agrega al remitente de los reportes por mail en CCO

---

monitoreo/apps/dashboard/models/indicators.py
monitoreo/apps/dashboard/models/querysets.py
monitoreo/apps/dashboard/series_csv_generators.py
monitoreo/apps/dashboard/tests/indicators_files_tests.py

Closes #254 
- Agrega un metodo al queryset para filtrar de acuerdo a los indicadores que tienen el campo `series` en True
- Agrega tests del comportamiento

Apply boolean filter on series

---

monitoreo/apps/dashboard/admin/indicators.py
monitoreo/apps/dashboard/management/commands/validate_indicators.py
monitoreo/apps/dashboard/management/import_utils.py
monitoreo/apps/dashboard/management/indicators_validator.py
monitoreo/apps/dashboard/tests/samples/indicators_sample.csv
monitoreo/apps/dashboard/tests/samples/malformed_date.csv
monitoreo/apps/dashboard/tests/samples/network_indicators_sample.csv
monitoreo/apps/dashboard/tests/samples/null_indicators.csv
monitoreo/apps/dashboard/tests/samples/repeated_indicators.csv
monitoreo/apps/dashboard/tests/samples/updated_indicators.csv

Closes #283 
- Actualiza los headers de csv en las rutinas de vañidación e importación de indicadores
- Actualiza los headers en los casos de tests

283 headers importacion indicadores

---

monitoreo/apps/dashboard/migrations/0056_federation_task_callable_str_migration.py
monitoreo/apps/dashboard/migrations/0057_normalize_indicator_values_import.py

Resolución del bug derivado del issue: #244.
Se migran los callable_str que quedaron mal armados en los environments

migracion para corregir los callable_str de los stages en monitoreo

---

conf/settings/base.py
requirements/base.txt

Django admin shortcuts

---

monitoreo/apps/dashboard/tests/validation_report_tests.py
monitoreo/templates/reports/validation.html
monitoreo/templates/reports/validation.txt

Modifico palabra inspeccion' en reporte de validacion.
